export const FETCH_BOOKLIST_REQUEST = 'FETCH_BOOKLIST_REQUEST'
export const FETCH_BOOKLIST_SUCCESS = 'FETCH_BOOKLIST_SUCCESS'
export const FETCH_BOOKLIST_FAILURE = 'FETCH_BOOKLIST_FAILURE'

export const SEARCH_BOOKLIST = 'SEARCH_BOOKLIST'
export const SORT_BOOKLIST = 'SORT_BOOKLIST'

export const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART';